### PR TITLE
Milestone 0.2.0

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by Scrum** [comment]
@maltsev approve ?

**Comment by maltsev** [comment]
Sure. Thanks for adding plugins support!

Shouldn't we remove `package-lock.json` from the repository?

**Comment by Scrum** [comment]
@maltsev not necessarily), Please if you know that you can disappear for a long time, give access to npm so that we can promptly make changes. This is a very common problem.

With hope for understanding

**Comment by Scrum** [comment]
@maltsev and publish this in npm please )

**Comment by maltsev** [comment]
I see. Thanks! I published the package to npm.

I don't plan to disappear, but it'd be better if could publish new versions when needed as I don't have much time to do that right now. I'll give you access.

**Comment by Scrum** [comment]
@maltsev 
> I'll give you access.

Cool, i wrote you on email because twitter do not hurt if you do not read me (

**Pull request merged**
